# Server configuration
server.port=8080
server.servlet.context-path=/
spring.application.name=UK Tax Calculator

# Thymeleaf configuration
spring.thymeleaf.cache=false
spring.thymeleaf.enabled=true
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# Logging configuration
logging.level.root=INFO
logging.level.com.mariusrubin.calculationengine=DEBUG
logging.level.org.springframework.web=INFO