name: GraalVM build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '25'
          distribution: 'graalvm-community' # See 'Options' for all available distributions
          version: 25.0.2
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Check GraalVM installed
        run: |
          echo "GRAALVM_HOME: $GRAALVM_HOME"
          echo "JAVA_HOME: $JAVA_HOME"
          java --version
          native-image --version
      - name: Build using maven  # https://graalvm.github.io/native-build-tools/latest/maven-plugin.html
        run: ./mvnw -Pnative -B package
